apiVersion: v1
kind: Service
metadata:
  name: appnotas-service
spec:
  sessionAffinity: ClientIP
  selector:
    app: appnotas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
